name: Check CoreOrchestrator
on: [push]

jobs:
  health-check:
    runs-on: self-hosted
    defaults:
      run:
        working-directory: /data
    # Quitamos la sección 'container' para evitar el conflicto de Node.js
    steps:
      - name: Clonar código
        uses: actions/checkout@v4

      - name: ¿Dónde estoy y qué veo?
        run: |
          echo "Mi ruta actual es:"
          pwd
          echo "Los archivos en esta carpeta son:"
          ls -la
          echo "Escribiendo archivo de prueba..."
          echo "Hola Alan desde el Runner" > prueba_conexion.txt

      - name: Reporte de Hardware y Software
        run: |
          echo "--- REPORTE DE SISTEMA ---"
          echo "Arquitectura de la Raspberry:" && uname -m
          echo "Espacio en el SSD:" && df -h /
          
      - name: Probar Docker y .NET
        run: |
          echo "Verificando que el Runner puede lanzar contenedores:"
          docker run --rm mcr.microsoft.com/dotnet/sdk:8.0 dotnet --version
